TX_POWER = 1;
TX_FREQ = 915e6;
TX_HEIGHT = 10;

siteA = txsite(Name="SiteA", ...
    Latitude=35.6164372, ...
    Longitude=-111.592136, ...
    AntennaHeight=TX_HEIGHT, ...
    TransmitterFrequency=TX_FREQ, ...
    TransmitterPower=TX_POWER);

siteF = txsite(Name="SiteF", ...
    Latitude=35.593743, ...
    Longitude=-111.653278, ...
    AntennaHeight=TX_HEIGHT, ...
    TransmitterFrequency=TX_FREQ, ...
    TransmitterPower=TX_POWER);

siteK = txsite(Name="SiteK", ...
    Latitude=35.590627, ...
    Longitude=-111.633156, ...
    AntennaHeight=TX_HEIGHT, ...
    TransmitterFrequency=TX_FREQ, ...
    TransmitterPower=TX_POWER);

siteL = txsite(Name="SiteL", ...
    Latitude=35.626898, ...
    Longitude=-111.602013, ...
    AntennaHeight=TX_HEIGHT, ...
    TransmitterFrequency=TX_FREQ, ...
    TransmitterPower=TX_POWER);

pm = propagationModel("longley-rice", ...
    AntennaPolarization="vertical", ...
    GroundConductivity=0.005, ...
    GroundPermittivity=6.700, ...
    AtmosphericRefractivity=256.3, ...
    ClimateZone="continental-temperate", ...
    SituationVariabilityTolerance=0.5, ...
    TimeVariabilityTolerance=0.9);

disp("Processing SiteA")
siteAPd = coverage(siteA, pm, ...
    ReceiverAntennaHeight=2, ...
    SignalStrengths=-150:0, ...
    MaxRange=2500, ...
    Resolution=30);
writetable(siteAPd.Data, "../data/itm/siteA.csv");

disp("Processing SiteF")
siteFPd = coverage(siteF, pm, ...
    ReceiverAntennaHeight=2, ...
    SignalStrengths=-150:0, ...
    MaxRange=2500, ...
    Resolution=30);
writetable(siteFPd.Data, "../data/itm/siteF.csv");

disp("Processing SiteK")
siteKPd = coverage(siteK, pm, ...
    ReceiverAntennaHeight=2, ...
    SignalStrengths=-150:0, ...
    MaxRange=2500, ...
    Resolution=30);
writetable(siteKPd.Data, "../data/itm/siteK.csv");

disp("Processing SiteL")
siteLPd = coverage(siteL, pm, ...
    ReceiverAntennaHeight=2, ...
    SignalStrengths=-150:0, ...
    MaxRange=2500, ...
    Resolution=30);
writetable(siteLPd.Data, "../data/itm/siteL.csv");