TX_LON = -111.632100;
TX_LAT = 35.590789;

pm = propagationModel("longley-rice", ...
    AntennaPolarization="vertical", ...
    GroundConductivity=0.005, ...
    GroundPermittivity=6.700, ...
    AtmosphericRefractivity=256.3, ...
    ClimateZone="continental-temperate", ...
    SituationVariabilityTolerance=0.5, ...
    TimeVariabilityTolerance=0.9);

tx = txsite(Name="ITM", ...
    Latitude=TX_LAT, ...
    Longitude=TX_LON, ...
    AntennaHeight=10, ...
    TransmitterFrequency=915e6, ...
    TransmitterPower=1);

pd = coverage(tx, pm, ...
    ReceiverAntennaHeight=2, ...
    SignalStrengths=-150:0, ...
    MaxRange=2500, ...
    Resolution=30);

writetable(pd.Data, "../data/itm.csv");